export enum ActionConstent {
    SET_DRINKS = 'SET_DRINKS',
    SET_CONSUMED_DRINK = 'SET_CONSUMED_DRINK',
    SET_APP_LOADER = 'SET_APP_LOADER',
    SET_USER_DATA = 'SET_USER_DATA',
    SET_IN_TAKEN = 'SET_IN_TAKEN'
}
